apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-cert
  namespace: namespace
spec:
  secretName: example-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - 'example.com'